### ISSUE TITLE
Possibility of a MessageRead trait?

### ISSUE THREAD

**Issue by daboross** [tafia/quick-protobuf#78] opened 2017-11-14 23:20 UTC
This isn't a big problem, but I was wondering if there's any technical reason why from_reader is generated as an independent method rather than on some MessageRead trait.

If it were a trait, it would be possible to simplify reading code - and not have to specify `TypeName::from_reader` as an argument to `BytesReader.read_message`. It would also allow consumers to write generic utility methods useful for all of their messages.

Is there a specific advantage to the way quick-protobuf does this now that I'm not seeing?

**Comment by tafia** [comment] 2017-11-15 04:41
Unfortunately this is not possible today. I can't remember exactly the root cause but the compiler wasn't happy to have struct and traits with lifetimes.

But feel free to try it. It would indeed be much nicer.

**Comment by daboross** [comment] 2017-11-15 06:01
Ah cool, that's reasonable.

I might try to get it working, if the lifetime errors are what I think they are it might be like what serde ran into for the 0.9 release. I think they solved it by having all lifetimes associated with traits, and using `for<'a> Deserialize<'a>` wherever the traits were specified - but I'll have to see if this works for quick-protobuf as well.

**Comment by tafia** [comment] 2017-11-15 06:25
> using for<'a> Deserialize<'a> wherever the traits were specified

I think I tried that too. But things have probably changed on the compiler side since then.

**Comment by daboross** [comment] 2017-11-15 06:39
Ah, that might be true. Is there a minimum rust version that quick-protobuf maintains currently?

I have a trait which seems to work as far as I can tell in the latest rust [here](https://github.com/daboross/quick-protobuf/tree/impl-to-trait), but I'm not sure what all disadvantages adding it would have.

**Comment by tafia** [comment] 2017-11-15 06:42
There is no minimum version to be supported. Only stable.

**Comment by daboross** [comment] 2017-11-15 06:45
Alright, that's reasonable. I guess I'll make a PR then?

The library is really nice to work with right now. I'm hesitating mainly for fear of reducing usability since I don't know the majority of use cases.

**Comment by tafia** [comment] 2017-11-23 02:47
#85 merged. Thanks again!

**Closed by tafia** 2017-11-23 02:47 UTC
